# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3044d62353dc4dc9ec07c77c66cb9ec239bef8d297ac10c5878fe351111c7222ee29da0b6de28e6e2dffb5cd5610153c2722f72f687590eda51b8b11043b63e2

test:
  secret_key_base: 9bcee0ca30088b7a00eb8b0ed497d1da1a1d235d5ad35a36459e891ff525f3682b7c7da5c3daa957d4e8d51c42aa860b4ba01ee5091f587fbd76b8edcbad4adb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
